# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/HTML.gitlab-ci.yml

# Full project: https://gitlab.com/pages/plain-html
image: busybox

pages:
  only:
  - gl-pages
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL/documentation/fanappodasyncsdk"
    - mkdir .public
    - cp -r ./* .public
    - rm -rf public
    - mv .public public
    - mv .docs/* public
  artifacts:
    paths:
      - public
